[colors.bright]
black = "0x475266"
blue = "0x59C2FF"
cyan = "0xC7FFFC"
green = "0xAAD94C"
magenta = "0xD2A6FF"
red = "0xF07178"
white = "0xFAFAFA"
yellow = "0xE6B673"

[colors.normal]
black = "0x000000"
blue = "0x39BAE6"
cyan = "0x95E6CB"
green = "0x7FD962"
magenta = "0x6C5980"
red = "0xD95757"
white = "0xFFFFFF"
yellow = "0xFFB454"

[colors.primary]
background = "0x0D1017"
foreground = "0xBFBDB6"

[font]
size = 13

[font.normal]
family = "Jetbrains Mono"
style = "Regular"
