monitor = DP-2, 1920x1080@60, 0x0, 1, vrr, 0
monitor = DP-3, 2560x1440@165.0, 1920x0, 1, vrr, 1
monitor = , preferred, auto, 1

workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:DP-3, default:true

exec-once = xrandr --output DP-3 --primary

cursor {
  no_break_fs_vrr = 1
  min_refresh_rate = 48
}
