[colors.primary]
background = "0x0A0E14"
foreground = "0xCBCCC6"

[colors.normal]
black = "0x1D202F"
red = "0xFF3333"
green = "0xC2D94C"
yellow = "0xE6B450"
blue = "0x39BAE6"
magenta = "0xA37ACC"
cyan = "0x59C2FF"
white = "0xB3B1AD"

[colors.bright]
black = "0x1D202F"
red = "0xFF3333"
green = "0xC2D94C"
yellow = "0xE6B450"
blue = "0x39BAE6"
magenta = "0xA37ACC"
cyan = "0x59C2FF"
white = "0xCBCCC6"

[font]
size = 13

[font.normal]
family = "Jetbrains Mono"
style = "Regular"
